import type { Metadata } from "next";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import BootstrapClient from './components/globalComponents/BootstrapClient';

export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by create next app",
  icons: {
    icon: '/a.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />
      </head>
      <body style={{ margin: 0, padding: 0, fontFamily: "sans-serif", fontSize: 16 }}>
        <BootstrapClient />
        {children}
      </body>
    </html>
  );
}
